// ─── Tile Product Data ──────────────────────────────────────────────────────
// Images use Unsplash for high-quality placeholders; swap image_url for real assets.

export const SIZES = ['All', '600×600mm', '600×1200mm', '800×800mm', '800×1600mm', '1200×2400mm']
export const FINISHES = ['All', 'High Gloss', 'Matt', 'Carving', 'Satin', 'Lappato']
export const APPLICATIONS = ['All', 'Floor', 'Wall', 'Outdoor', 'Bathroom']

export const products = [
  {
    id: 1,
    name: 'Alpine White',
    series: 'Alpine Project',
    size: '800×1600mm',
    finish: 'High Gloss',
    application: ['Floor', 'Wall'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Pure White',
    image_url: '/tiles/ALPINE-WHITEPJ-16341-1-80X160_EDIT20_P1.jpg',
    badge: 'Bestseller',
    description: 'A brilliant, light-reflective white slab with subtle cool undertones. Part of the Alpine Project series, ideal for minimalist architectural spaces.',
  },
  {
    id: 2,
    name: 'Antique Beige',
    series: 'Antique V1',
    size: '800×1600mm',
    finish: 'Matt',
    application: ['Floor', 'Wall', 'Outdoor'],
    material: 'Porcelain',
    thickness: '10mm',
    color: 'Beige',
    image_url: '/tiles/ANTIQUE-BEIGEANTIQUE-BEIGE_V1_80X160_F1.jpg',
    badge: 'New',
    description: 'Warm earth tones with a sophisticated matte finish. Perfectly balances traditional warmth with modern large-format durability.',
  },
  {
    id: 3,
    name: 'Arezzo Bianco',
    series: 'Arezzo Collection',
    size: '800×1600mm',
    finish: 'High Gloss',
    application: ['Floor', 'Wall', 'Bathroom'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Soft White',
    image_url: '/tiles/AREZZO-BIANCOAREZZO-BIANCO-P1-EDIT7.jpg',
    badge: '',
    description: 'Luminous soft white with delicate grain textures. Inspired by the classic Italian Arezzo stones, refined for contemporary high-end interiors.',
  },
  {
    id: 4,
    name: 'Arezzo Gris',
    series: 'Arezzo Collection',
    size: '800×1600mm',
    finish: 'Matt',
    application: ['Wall', 'Bathroom', 'Floor'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Cool Grey',
    image_url: '/tiles/AREZZO-GRISAREZZO-GRIS-P1-EDIT7.jpg',
    badge: 'Premium',
    description: 'A sophisticated cool-grey surface with a smooth architectural finish. Part of the Arezzo series, designed for industrial and minimalist contexts.',
  },
  {
    id: 5,
    name: 'Astana Aqua',
    series: 'Astana Series',
    size: '800×1600mm',
    finish: 'High Gloss',
    application: ['Wall', 'Bathroom', 'Floor'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Aqua / Blue',
    image_url: '/tiles/ASTANA-AQUAREIMS-AQUA-P1.jpg',
    badge: 'Exclusive',
    description: 'Exotic aqua-infused marble patterns on a mirror-polished porcelain slab. A high-impact choice for feature walls and statement bathroom floors.',
  },
  {
    id: 6,
    name: 'Celion Bianco',
    series: 'Celion Series',
    size: '800×1600mm',
    finish: 'Satin',
    application: ['Wall', 'Bathroom', 'Floor'],
    material: 'Porcelain',
    thickness: '6mm',
    color: 'Bone White',
    image_url: '/tiles/CELION-BIANCOCELION-BIANCO-P1.jpg',
    badge: 'Signature',
    description: 'A pure, bone-white surface with a subtle satin texture. Provides a serene backdrop for both residential and commercial projects.',
  },
  {
    id: 7,
    name: 'Antico Beige',
    series: 'Antique V2',
    size: '800×1600mm',
    finish: 'Matt',
    application: ['Floor', 'Outdoor'],
    material: 'Porcelain',
    thickness: '10mm',
    color: 'Warm Beige',
    image_url: '/tiles/ANTIQUE-BEIGEZS01807_AnticoBe-ige_1.jpg',
    badge: '',
    description: 'Richer beige tones with authentic stone texture. Part of the Antico series, designed for warm, heritage-inspired outdoor and indoor flooring.',
  },
  {
    id: 8,
    name: 'Bosco Grey',
    series: 'Grand Slab',
    size: '1200×2400mm',
    finish: 'High Gloss',
    application: ['Floor', 'Wall'],
    material: 'Porcelain',
    thickness: '6mm',
    color: 'Graphite Grey',
    image_url: '/tiles/BOSCO-GREYfp25759-2-120x240-JC1-JC6-JC2-P1.jpg',
    badge: 'Large Format',
    description: 'Monumental 1200x2400mm slabs in a deep graphite grey. Mirror-polished finish makes it a stunning choice for high-end commercial lobbies and modern villas.',
  },
  {
    id: 9,
    name: 'Brescia Grey',
    series: 'Classic Marble',
    size: '800×1600mm',
    finish: 'High Gloss',
    application: ['Floor', 'Wall'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Grey / White',
    image_url: '/tiles/BRESCIA-GREYMt-800x1600-04-EDIT12_P1.jpg',
    badge: '',
    description: 'Classic Brescia marble patterns with intricate grey veining on a light base. A timeless architectural surface for premium interior projects.',
  },
  {
    id: 10,
    name: 'Dyna Gold',
    series: 'Precious Stones',
    size: '800×1600mm',
    finish: 'High Gloss',
    application: ['Floor', 'Wall'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Golden Beige',
    image_url: '/tiles/DYNA-GOLDK21455_B_EDIT9_P1.jpg',
    badge: 'Premium',
    description: 'Opulent golden dyna marble textures with a high-gloss finish. Adds a sense of luxury and warmth to large-scale residential living areas.',
  },
  {
    id: 11,
    name: 'Forest Wood Amber',
    series: 'Timber Series',
    size: '200×1200mm',
    finish: 'Matt',
    application: ['Floor', 'Wall'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Amber Wood',
    image_url: '/tiles/FOREST-WOOD-AMBERJT_WOOD_04_P1-EDIT-JC6-1-P1-1.jpg',
    badge: 'Wood Look',
    description: 'Authentic amber-toned wood plank porcelain. Combines the organic warmth of real timber with the durability and weather-resistance of ceramics.',
  },
  {
    id: 12,
    name: 'Forest Wood Brown',
    series: 'Timber Series',
    size: '200×1200mm',
    finish: 'Matt',
    application: ['Floor', 'Wall'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Dark Brown',
    image_url: '/tiles/FOREST-WOOD-BROWN01.jpg',
    badge: '',
    description: 'Deep espresso tones with realistic grain patterns. Ideal for creating a cozy, natural ambiance in bedrooms or rustic hospitality spaces.',
  },
  {
    id: 13,
    name: 'Forest Wood Ocra',
    series: 'Timber Series',
    size: '200×1200mm',
    finish: 'Matt',
    application: ['Floor', 'Wall'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Light Oak',
    image_url: '/tiles/FOREST-WOOD-OCRA01.jpg',
    badge: '',
    description: 'Lighter oak-inspired tones for a Scandinavian aesthetic. High-durability porcelain planks that resist scratching and moisture.',
  },
  {
    id: 14,
    name: 'Fossil Grey',
    series: 'Texture Studio',
    size: '600×1200mm',
    finish: 'Matt',
    application: ['Floor', 'Outdoor'],
    material: 'Porcelain',
    thickness: '10mm',
    color: 'Ash Grey',
    image_url: '/tiles/FOSSIL-GREYFOSSIL_GREY.jpg',
    badge: '',
    description: 'Minimalist ash-grey surface with subtle fossil-like fossilization. Perfect for high-traffic commercial environments and industrial interiors.',
  },
  {
    id: 15,
    name: 'Lucido Mocha',
    series: 'Lucido Collection',
    size: '800×1600mm',
    finish: 'High Gloss',
    application: ['Floor', 'Wall'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Mocha / Brown',
    image_url: '/tiles/LUCIDO-MOCHA17759_UTIL_MOTTO-P1-JC20-23-P2.jpg',
    badge: 'New',
    description: 'Sophisticated mocha-brown marble with deep, glossy depth. A contemporary take on classic dark stone surfaces.',
  },
  {
    id: 16,
    name: 'Portoro Black',
    series: 'Luxury Black',
    size: '800×1600mm',
    finish: 'High Gloss',
    application: ['Wall', 'Bathroom'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Black / Gold',
    image_url: '/tiles/PORTORO-BLACKea11173-A-BR-JC2.jpg',
    badge: 'Exclusive',
    description: 'The pinnacle of luxury: deep black porcelain with striking golden-yellow veining. Perfect for bathroom feature walls and dramatic foyers.',
  },
  {
    id: 17,
    name: 'Saint Laurent',
    series: 'Luxury Black',
    size: '800×1600mm',
    finish: 'High Gloss',
    application: ['Wall', 'Bathroom'],
    material: 'Porcelain',
    thickness: '9mm',
    color: 'Black / White',
    image_url: '/tiles/SAINT-LAURENTea11157-A-NSL_JC5-EDIT2_P1-EDIT6.jpg',
    badge: 'Designer Choice',
    description: 'High-contrast black marble with bold white and bronze linear veining. Brings French elegance and architectural drama to any surface.',
  },
]
